#include <stdio.h>
#include <string.h>
#include "asn1crt.h"
#include "asn1crt_mempool.h"
#include "satellite.h"

void hexdump(const char* desc, const void* addr, size_t len) {
    printf("%s (%zu bytes):\n", desc, len);
    const unsigned char* pc = (const unsigned char*)addr;
    for (size_t i = 0; i < len; i++) {
        printf("%02x ", pc[i]);
        if ((i+1) % 8 == 0) printf("\n");
    }
    printf("\n");
}

void test_decoding() {
    byte buffer[4096];
    MemPool pool;
    MemPool_Init(&pool, buffer, sizeof(buffer));

    T_TelemetryFrame* frame = MemPool_Alloc(&pool, sizeof(T_TelemetryFrame));
    if (!frame) {
        printf("Allocation failed for %zu bytes\n", sizeof(T_TelemetryFrame));
        return;
    }

    /* Verified PER-encoded test data */
       byte test_data[] = {
    0x00, 0x00, 0x00, 0x01, 0xfa, 0x00, 0x00, 0x00,
    0x49, 0xc4, 0x36, 0xb1, 0x38, 0x82, 0x0a
};
	
	printf("Raw test data as seen by decoder:\n");
	for (size_t i = 0; i < sizeof(test_data); i++) {
    	printf("%02x ", test_data[i]);
    	if ((i+1) % 8 == 0) printf("\n");
	}

    hexdump("Test Data", test_data, sizeof(test_data));

    BitStream bs;
    BitStream_Init(&bs, test_data, sizeof(test_data));
	bs.currentByte = 0;
	bs.currentBit = 0;

    int errCode;
    if (T_TelemetryFrame_Decode(frame, &bs, &errCode)) {
        printf("\n=== DECODE SUCCESS ===\n");
        printf("Bytes processed: %ld/%zu\n", bs.currentByte, sizeof(test_data));
        printf("Frame count: %lu\n", frame->header.frameCount);
        printf("Payload type: %d\n", frame->payload.kind);
	
	printf("CHOICE tag value in test data: 0x%02x\n", test_data[9]);
   	printf("ASN.1 CHOICE index decoded: %d\n", frame->payload.kind);
	printf("Expected housekeeping_PRESENT value: %d\n", housekeeping_PRESENT);	
	printf("After decoding:\n");

    	printf("- Header timeStamp seconds: %lu\n", frame->header.timestamp.seconds);
    	printf("- Header timeStamp subseconds: %lu\n", frame->header.timestamp.subseconds);
   	printf("- Header frameType: %lu\n", frame->header.frameType);
	printf("- Header frameCount: %lu\n", frame->header.frameCount);
	printf("- Payload kind: %u\n", frame->payload.kind);
            
        if (frame->payload.kind == 1) {
            printf("Housekeeping data:\n");
            printf("- Main bus: %lu mV\n", frame->payload.u.housekeeping.voltages.mainBus);
            printf("- Temperature: %ld C\n", frame->payload.u.housekeeping.temperature.arr[0]/10);
        } else {
            printf("UNEXPECTED payload type! Check CHOICE tags.\n");
            printf("First payload byte: 0x%02x\n", test_data[9]);
        }
    } else {
        printf("\nDECODE FAILED (Error: %d)\n", errCode);
        printf("Bytes processed: %ld/%zu\n", bs.currentByte, sizeof(test_data));
    }
}

         void test_with_generated_data() {
    // Create buffers for encoding/decoding
    byte encBuffer[4096];
    BitStream encBitStream;
    BitStream_Init(&encBitStream, encBuffer, sizeof(encBuffer));

    // Create a simpler frame
    T_TelemetryFrame testFrame;
    T_TelemetryFrame_Initialize(&testFrame);

    // Just set header values
    testFrame.header.timestamp.seconds = 1;
    testFrame.header.timestamp.subseconds = 1000;
    testFrame.header.frameType = 0;
    testFrame.header.frameCount = 1;

    // Set minimal payload
    testFrame.payload.kind = housekeeping_PRESENT;
    
    // Don't set any housekeeping fields - leave them at default values

    // Encode the frame
    int errCode;
    if (T_TelemetryFrame_Encode(&testFrame, &encBitStream, &errCode, TRUE)) {
        printf("Encoding successful! Generated %ld bytes\n", encBitStream.currentByte);
        
        // Print the generated bytes
        printf("Generated PER-encoded data (header-only):\n");
        for (int i = 0; i < encBitStream.currentByte; i++) {
            printf("%02x ", encBuffer[i]);
            if ((i+1) % 8 == 0) printf("\n");
        }
        printf("\n");
        
        // Try decoding
        BitStream decBitStream;
        BitStream_Init(&decBitStream, encBuffer, encBitStream.currentByte);
        
        T_TelemetryFrame decodedFrame;
        if (T_TelemetryFrame_Decode(&decodedFrame, &decBitStream, &errCode)) {
            printf("Decoding successful!\n");
            // Print decoded values
        } else {
            printf("Decoding failed with error: %d\n", errCode);
        }
    } else {
        printf("Encoding failed with error: %d\n", errCode);
    }
}

void test_minimal() {
    // Create a minimal TelemetryFrame with just enough to test
    T_TelemetryFrame frame;
    T_TelemetryFrame_Initialize(&frame);
    
    // Set it to housekeeping with minimal data
    frame.payload.kind = housekeeping_PRESENT;
      
    printf("Status field type information:\n");
   
    memset(&frame.payload.u.housekeeping.status, 0, sizeof(frame.payload.u.housekeeping.status));

    // Try different ways to set the status field
   // frame.payload.u.housekeeping.status.arr[0] = 0; // All bits clear
    
    // Encode
    byte buffer[256];
    BitStream bs;
    BitStream_Init(&bs, buffer, sizeof(buffer));
    
    int errCode;
    if (T_TelemetryFrame_Encode(&frame, &bs, &errCode, TRUE)) {
        printf("Minimal encode successful: %ld bytes\n", bs.currentByte);
        
        // Decode the same data
        BitStream decodeBs;
        BitStream_Init(&decodeBs, buffer, bs.currentByte);
        
        T_TelemetryFrame decodedFrame;
        if (T_TelemetryFrame_Decode(&decodedFrame, &decodeBs, &errCode)) {
            printf("Minimal decode successful\n");
        } else {
            printf("Minimal decode failed: error %d\n", errCode);
        }
    } else {
        printf("Minimal encode failed: error %d\n", errCode);
    }
} 

int main () {
    printf("===== Minimal Test =====\n");
    test_minimal();

    printf("===== Telemetry Decoder Test =====\n");
    test_decoding();
    printf("\n===== Generated Test Vector Test =====\n");
    test_with_generated_data();
    return 0;
}
